-- Purpose: H2 in-memory — fresh tables each run (profile: embedded).
DROP TABLE IF EXISTS usage_daily;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS subscription_plans;

CREATE TABLE subscription_plans (
    id INT NOT NULL PRIMARY KEY,
    code VARCHAR(32) NOT NULL,
    display_name VARCHAR(64) NOT NULL,
    max_file_bytes BIGINT NOT NULL,
    max_batch_files INT NOT NULL DEFAULT 1,
    ops_per_day INT NOT NULL,
    history_days INT NOT NULL DEFAULT 0,
    ads_enabled BOOLEAN NOT NULL DEFAULT TRUE,
    price_usd DOUBLE NOT NULL DEFAULT 0.0
);

INSERT INTO subscription_plans (id, code, display_name, max_file_bytes, max_batch_files, ops_per_day, history_days, ads_enabled, price_usd) VALUES
(1, 'GUEST', 'Guest', 52428800, 1, 10, 0, TRUE, 0.0),
(2, 'FREE', 'Free', 104857600, 1, 25, 0, TRUE, 0.0),
(3, 'INDIVIDUAL', 'Individual', 5368709120, 25, 3000, 7, FALSE, 9.99),
(4, 'BUSINESS', 'Business', 53687091200, 500, 50000, 15, FALSE, 49.99);

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    display_name VARCHAR(120),
    subscription_plan_id INT NOT NULL DEFAULT 2,
    plan_expires_at TIMESTAMP,
    stripe_customer_id VARCHAR(128),
    is_active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE usage_daily (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usage_date DATE NOT NULL,
    subject_key VARCHAR(128) NOT NULL,
    operation_count INT NOT NULL DEFAULT 0,
    CONSTRAINT uk_usage_subject_day UNIQUE (usage_date, subject_key)
);
